### ISSUE TITLE
Cargo build errors

### ISSUE THREAD

**Issue by GerhardLiebenberg** [thasarito/simple-arbitrage-rs#1]
Good day. I am trying to build the simple-arbitrage-rs app.
Cargo build gives me the following errors:

**_Attempt-1_**
**Cargo.toml:**
ethers = { git = "https://github.com/thasarito/ethers-rs", feature="abigen" }
**Error:**
    Updating git repository `https://github.com/thasarito/ethers-rs`
    Updating crates.io index
    Updating git repository `https://github.com/rust-ethereum/ethabi`
    Updating git repository `https://github.com/hyperledger-labs/solang`
error: failed to select a version for `generic-array`.
    ... required by package `elliptic-curve v0.11.6`
    ... which satisfies dependency `elliptic-curve = "^0.11.6"` (locked to 0.11.6) of package `ecdsa v0.13.4`
    ... which satisfies dependency `ecdsa = "^0.13.4"` of package `ethers-core v0.6.0 (https://github.com/thasarito/ethers-rs#a77bf845)`

**_Attempt-2_**
**Cargo.toml:**
ethers = { version = "0.6.2", features = ["abigen"] }
**Error:**
error[E0432]: unresolved import `ethers::contract::MultiAbigen`
 --> build.rs:2:24
  |
2 | use ethers::contract::{MultiAbigen};
  |                        ^^^^^^^^^^^ no `MultiAbigen` in `contract`

Do I need to install any other software before attempting the build?

**Comment by thasarito** [comment]
Maybe try replacing `ethers = { git = "https://github.com/thasarito/ethers-rs", feature="abigen" }` with the official repo.

https://github.com/gakonst/ethers-rs

**Comment by GerhardLiebenberg** [comment]
I tried that as well. Same error.

It looks like MultiAbigen is a new feature. Perhaps that is why it is not in the crate's version = "0.6.2" yet.
Do you think the crate has a nightly version I could try?

**Comment by thasarito** [comment]
Have you tried `cargo clean` and build again.

**Comment by thasarito** [comment]
Also, may I ask what your purpose of running?

FYI that this is incomplete and the arbitrage logic may not be correct.

**Comment by GerhardLiebenberg** [comment]
I ran cargo clean, but same errors.

I want to run the code to learn how to interact with the flashbots contracts.
I did not get it working using the ethers-rs examples.
Don’t worry about incompleteness :-)

**Comment by thasarito** [comment]
Can you get it to work now?

**Comment by GerhardLiebenberg** [comment]
I got the parts that I need working - by duplicating them in a new application. 
I have not yet found the parts that gave me problems in the first place. 
I will let you know if I find anything not working.
Thanx for your help.
